name: Build KMP iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar o Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar cache do Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Configurar Ambiente e Diretórios (Solução Arquitetural)
        run: |
          # 1. Garante que o Gradle é executável na pasta raiz
          chmod +x ./gradlew
          
          # 2. Cria o arquivo que o Xcode procura dentro da pasta do projeto iOS
          # Isso injeta o caminho real do Java diretamente no escopo do Xcode
          echo "export JAVA_HOME=$JAVA_HOME" > iosApp/.xcode.env
          
          # 3. Fornece a rota do Android SDK, exigida pelo Gradle no background
          echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: 1. Compilar o código Kotlin (Shared XCFramework)
        run: ./gradlew :shared:assembleSharedDebugXCFramework

      - name: 2. Compilar o Projeto Xcode (App iOS)
        run: |
          # set -o pipefail impede que o Xcode esconda o erro real do shell script
          set -o pipefail
          xcodebuild clean build \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO | xcbeautify
